---
# task file for Update specific argument value in a passwd rule
  - name: No username in password
    community.general.pamd:
      name: common-password
      type: password
      control: requisite
      module_path: pam_pwquality.so
      module_arguments: 'reject_username enforce_for_root'
      state: args_present

