---
# defaults file for tcpwrappers_rules

tcpwrappers_allow:
  - daemon: 'sshd'
    clients:
      - '178.165.77.146'

tcpwrappers_allow_all_connections: false  #Defines if all connections are allowed

tcpwrappers_deny:
  - daemon: 'sshd'
    clients:
      - 'ALL'

tcpwrappers_deny_all_connections: true  #Defines if all connections are denied
